### ISSUE TITLE
[help request]想在TextSetter里添加一个属性，无法保存

### ISSUE THREAD

**Issue by yangg** [sleepy-zone/fabritor-web#28]
有个小需求想看看能不能实现，没找到联系方法，只能发在这里了
我给 TextSetter/inex.tsx 里添加一个属性，但是光标离开再选中就消失了，能不能指导下，谢谢！
```
<FormItem
          name="key"
          label="Name"
        >
          <Input />
        </FormItem>
```
我想让下面这个输入框的值，能保存到导出的模板里
![image](https://github.com/sleepy-zone/fabritor-web/assets/409225/0ac33d7a-d575-428e-8178-1b8e402b731d)

**Comment by sleepy-zone** [comment]
没太看懂，请再详细描述下问题

**Comment by yangg** [comment]
> 没太看懂，请再详细描述下问题

修改了，添加了图片，麻烦看下

**Comment by sleepy-zone** [comment]
fabritor 里，可以直接将该属性 key 添加到 constants FABRITOR_CUSTOM_PROPS 内，在这里的属性都被会导出到 JSON 中（包括复制等场景。
https://github.com/sleepy-zone/fabritor-web/blob/main/src/utils/constants.tsx#L109

fabricjs 文档 [http://fabricjs.com/docs/fabric.Canvas.html#toJSON](http://fabricjs.com/docs/fabric.Canvas.html#toJSON)

**Comment by yangg** [comment]
> fabritor 里，可以直接将该属性 key 添加到 constants FABRITOR_CUSTOM_PROPS 内，在这里的属性都被会导出到 JSON 中（包括复制等场景。 https://github.com/sleepy-zone/fabritor-web/blob/main/src/utils/constants.tsx#L109
> 
> fabricjs 文档 http://fabricjs.com/docs/fabric.Canvas.html#toJSON

我在这个FABRITOR_CUSTOM_PROPS 这个变量里加了 个 key，还是不行，
1. 现在只加了 TextSetter 里，如果从一个 Text 点击另一个 Text 时，刚才输入的值还是在
2. 点击其它不是 Text 的，再点击回来就清空了

**Comment by sleepy-zone** [comment]
添加后，是否调用了 object.set(key, value) ？

**Comment by yangg** [comment]
> 添加后，是否调用了 object.set(key, value) ？
默认已经有了
![image](https://github.com/sleepy-zone/fabritor-web/assets/409225/d5230075-b967-4316-bd3b-007f7d653436)

**Comment by sleepy-zone** [comment]
那应该没有问题，其他属性也是这样给的。

建议给一个在线代码仓库，写明需要做的事情，再看一下。

**Comment by yangg** [comment]
https://github.com/yangg/carelabel
部署在这里
https://carelabel.netlify.app/

**Comment by sleepy-zone** [comment]
代码仓库看不到，但你的key是不是写错了。。

**Comment by yangg** [comment]
> 代码仓库看不到，但你的key是不是写错了。。

sorry,现在可以看到了，你说的写错了是指什么？

**Comment by sleepy-zone** [comment]
```js
        <FormItem
          name="key"
          label="Name"
        >
          <Input />
        </FormItem>
```

你的 key 就是 “key”，其实已经通过 object.set 设置进去了。

但你没有通过 object  的更新将值回显。
```js
useEffect(() => {
    form.setFieldsValue()
  }, [object]);
```

这个问题先 close 了。

**Comment by yangg** [comment]
刚刚自己看到了，测试了 ok，正准备来回复，多谢了。
