### ISSUE TITLE
[建议] 基础形状的输入修改

### ISSUE THREAD

**Issue by ouyoungs** [sleepy-zone/fabritor-web#29]
矩形的长宽、圆角弧度、圆的半径，应该可以按照输入框输入值进行修改，建议操作面板添加这个功能

**Comment by sleepy-zone** [comment]
形状已经有 Control 控制大小（或者 Scale），不再建议增加输入值；也能避免 width/height 和 scale 对普通用户的困扰。

**Comment by ouyoungs** [comment]
意思就是不提供精确控制参数调节图形， 而是用手动拖拽等形式目测设计效果么

**Comment by sleepy-zone** [comment]
嗯。。这也是我一个纠结的点。
个人感觉这种在线工具确实无需精确设计，能保证基本的居中和辅助线对齐即可。
但显式的指定可能确实会更清晰一点。

我对比了两款在线设计工具，美图的 x-design 没有指定，canva 有调整位置的的表单，不仅有宽高，还有x y 位置。

**Comment by sleepy-zone** [comment]
不过我想到一个点，如果有人使用这个工具设计模板，可能显式设置位置和宽高比较重要。

**Comment by ouyoungs** [comment]
嗯，我也发现了几款开源的，都没有这个功能，不知道为何。但是实践中，稍微专业点的设计软件，都需要这个功能，比如 photoshop illustrator figma， 可能开发者并不是设计师，设计实践中，稍微复杂点的需求没有这些功能就无法完成。

**Comment by sleepy-zone** [comment]
一般来说，设计师应该不太会用类似的工具。从之前的内部实践来看，设计师会用专业的设计工具设计模板，然后导出成在线工具识别的格式，由其他用户继续编辑。

不过该功能是有用的，我先记到todo里，参照 canva 的交互。
<img width="362" alt="image" src="https://github.com/sleepy-zone/fabritor-web/assets/131369648/cad259fb-19b8-4413-a4ea-d2bfaf994ed2">

但这里有一定开发成本。fabricjs Control 默认是改变 Scale 而不是改变 width height。所以需要定制多边形（或者Path）的 Control 逻辑，只改变 width height，现在内部代码中只有 Rect 为了圆角不变形做了类似的逻辑。

**Comment by ouyoungs** [comment]
"设计师会用专业的设计工具设计模板，然后导出成在线工具识别的格式"

哈哈，这么说就明白了，但也没见这些项目都做相应的导入功能，那这个导入功能得特别牛逼。
所以很多项目正经的去做设计，基本上处于不可用状态。
比如一个矩形，怎么确定长是宽的2倍，怎么确定一个圆半径是画板尺寸的 1/2

比如要做一个类似朋友圈的9宫格，怎么横竖把画板3等分，然后把图片排列上去，

可以不那么精确，但是要有一个数值做参照，而不是凭感觉。
凭感觉根本做不到。

**Comment by sleepy-zone** [comment]
针对导入，我这边开了一个项目，https://github.com/sleepy-zone/sketch2fabritor ，Sketch 转 fabritor ，但还没开始😂

> 比如要做一个类似朋友圈的9宫格，怎么横竖把画板3等分，然后把图片排列上去，

这个是个很好的场景，这边我也记到 todo，除了给出精确数值，应该还有更好的交互 。

**Comment by yangg** [comment]
数值如果觉得不常用也可以像 https://design.palxp.cn/home  这家这样，做好了，但是折叠使用，可以做成设置，这样想使用的时候还是比较直观和方便的
