### ISSUE TITLE
bug: 导入新的图片，图片有点模糊，有什么解决办法吗？

### ISSUE THREAD

**Issue by egolink0** [sleepy-zone/fabritor-web#31]
![image](https://github.com/sleepy-zone/fabritor-web/assets/18521972/97d34598-2104-4742-9973-821b68223ca5)
左边是原图，右边是导入后看到的图

**Comment by sleepy-zone** [comment]
这个是因为 fabritor 在实现图片圆角时使用了 clipPath，而 fabritor Image ClipPath 会影响图片质量，详见 fabric.js issue : https://github.com/fabricjs/fabric.js/issues/5639

issue 给了两个解决方案：
一个是禁用图片缓存：`fabric.Object.prototype.needsItsOwnCache = () => false` 
一个是 `fabric.perfLimitSizeTotal = 16777216; // allows for up to 4096x4096 cache`

我尝试了下，会有所改善，但可能会影响性能。

另外，如果项目对图片圆角属性不是很care的话，可以直接放弃 fabritor 内的 FImage ，直接使用 Image 。

**Comment by egolink0** [comment]
> 这个是因为 fabritor 在实现图片圆角时使用了 clipPath，而 fabritor Image ClipPath 会影响图片质量，详见 fabric.js issue : [fabricjs/fabric.js#5639](https://github.com/fabricjs/fabric.js/issues/5639)
> 
> issue 给了两个解决方案： 一个是禁用图片缓存：`fabric.Object.prototype.needsItsOwnCache = () => false` 一个是 `fabric.perfLimitSizeTotal = 16777216; // allows for up to 4096x4096 cache`
> 
> 我尝试了下，会有所改善，但可能会影响性能。
> 
> 另外，如果项目对图片圆角属性不是很care的话，可以直接放弃 fabritor 内的 FImage ，直接使用 Image 。

感谢！
我尝试了下另一个方法  imageSmoothingEnabled 设置为 false，图片也清晰了，可以尝试下

**Comment by ab-etemadi** [comment]
> 这个是因为 fabritor 在实现图片圆角时使用了 clipPath，而 fabritor Image ClipPath 会影响图片质量，详见 fabric.js issue : [fabricjs/fabric.js#5639](https://github.com/fabricjs/fabric.js/issues/5639)
> 
> issue 给了两个解决方案： 一个是禁用图片缓存：`fabric.Object.prototype.needsItsOwnCache = () => false` 一个是 `fabric.perfLimitSizeTotal = 16777216; // allows for up to 4096x4096 cache`
> 
> 我尝试了下，会有所改善，但可能会影响性能。
> 
> 另外，如果项目对图片圆角属性不是很care的话，可以直接放弃 fabritor 内的 FImage ，直接使用 Image 。

I can't apply a clipPath to the image with this. Any updates?
