### ISSUE TITLE
Default image size

### ISSUE THREAD

**Issue by KriacoesMobile** [sleepy-zone/fabritor-web#37]
Firstly, congratulations on the incredible work and for sharing it with us.

I have two questions which are:

The first is how can I set an initial size for a new file? I try change _initSketch more dont work for me:

`private _initSketch () {
    const { width = 1200, height = 460 } = this._template || {};
    const sketch = new fabric.Rect({
      fill: '#ffffff',
      left: 0,
      top: 0,
      width,
      height,
      selectable: false,
      hasControls: false,
      hoverCursor: 'default',
      // @ts-ignore custom id 
      id: SKETCH_ID,
      // @ts-ignore custom desc
      fabritor_desc: 'by fabritor',
    });
    this.canvas.add(sketch);
    this.canvas.requestRenderAll();
    this.sketch = sketch;
    this._initResizeObserver();
    this._adjustSketch2Canvas();
  }`

And another question is could I show the way to compile it to use on my web page, after using yarn build it resulted in broken files.

I'm still new and noob at React ;)

I made a small implementation to have a json providing the UI texts I haven't done it in the entire project yet but as I want to use it with more languages I think this can help others if you want I can send you what I did maybe I can contribute in some way.

Thanks for your time

**Comment by sleepy-zone** [comment]
I apologize for the late reply.

The first question:
Have you previously worked with fabritor? If so, localStorage will store a piece of JSON, and upon refreshing the page, it will re-render, resulting in modifications to _initSketch's width and height not taking effect. You can delete the data in localStorage with the key of 'fabritor_web_json'; then the changes will take effect. If your application does not require local storage, you can set LOAD_FROM_LOCAL_WHEN_INIT and AUTO_SAVE_WHEN_CHANGE to false in config.ts.

And another question:
You can set codeSplitting to false in ice.config.mts to get a single js and css file. [https://v3.ice.work/docs/guide/basic/config#codesplitting](https://v3.ice.work/docs/guide/basic/config#codesplitting)

**Comment by KriacoesMobile** [comment]
Don't worry, I'm grateful for your answer and again thank you very much for
sharing this great project, I studied the structure of the project and its
technologies a little more, I had never worked with them and I realized
that many of my doubts are due to a lack of knowledge, ru I've been a
programmer for over 10 years, but I'm very new to typescript.

Em qui., 18 de abr. de 2024, 05:48, SleepyZone ***@***.***>
escreveu:

**Comment by sleepy-zone** [comment]
I should put i18n on my agenda now.  😂
