### ISSUE TITLE
Social Icons - Request

### ISSUE THREAD

**Issue by KriacoesMobile** [sleepy-zone/fabritor-web#38]
Hello friend, I would like to share an idea for a future update, which is the addition of social media icons would be very useful.

Social Icons: facebook, instagram, twitterX, tiktok, youtube, whatsapp, telegram, discord, github

Thank you very much in advance

**Comment by siwangqishiq** [comment]
these apps in my country is disabled ~~~  HAHAHA

**Comment by sleepy-zone** [comment]
That's a good idea, but I think developers can extend that part into their projects on their own. Thank you for your suggestion.

**Comment by KriacoesMobile** [comment]
Thank you for your feedback, how do I suggest more ideas is poor right here?

**Comment by sleepy-zone** [comment]
Feel free to suggest any project-related ideas in the issues.👏

**Comment by KriacoesMobile** [comment]
Thanks
