### ISSUE TITLE
feature需求

### ISSUE THREAD

**Issue by baifengbai** [sleepy-zone/fabritor-web#4]
您好，我想接入本地的stablediffusion做图片生成，从哪里接入比较好

**Comment by sleepy-zone** [comment]
您好！
比较建议的是，作为一个应用接入，在应用 Tab 下新增 AI 生图应用，类似内置的二维码一样，创建表单，生成图片插入到画板内。
如果想作为一个重点的功能，可以直接放到图片 Tab 下。
