### ISSUE TITLE
Issue with webpack loader for react-colors-beauty

### ISSUE THREAD

**Issue by porameht** [sleepy-zone/fabritor-web#41]
Good day, 

I encountered an issue while attempting to compile my project by nextjs. When running webpack, I encountered the following error message:

<img width="818" alt="Screenshot 2567-04-30 at 15 14 45" src="https://github.com/sleepy-zone/fabritor-web/assets/89307294/3e2c1565-a1bf-4767-b7ac-151b08a8d46c">

Can you any assistance or guidance on how to properly configure webpack to handle LESS files from the react-colors-beauty

Thank you vary much.

**Comment by sleepy-zone** [comment]
Sorry to see it so late, but I'm still on vacation in the country, I'll take a look at this later…

**Comment by sleepy-zone** [comment]
Firstly, to use LESS in Next.js, you can use the library [next-with-less](https://www.npmjs.com/package/next-with-less). However, there is another issue: [now.Global CSS cannot be imported from within node_modules](https://github.com/vercel/next.js/issues/19936).   I think I should publish a new version of react-colors-beauty to solve this issue.

**Comment by sleepy-zone** [comment]
now you can install  react-colors-beauty@2.0.0-beta.1.

then modify your next.config.mts to ignore less file

```ts
/** @type {import('next').NextConfig} */
const nextConfig = {
webpack: (config) => {
		config.module.rules.push({
			test: /node_modules\/react-colors-beauty/,
			resolve: {
				alias: {
					"./index.less": false,
          "./rc-color-picker.less": false,
				},
			},
		});

		return config;
	},
};

export default nextConfig;
```

last, import css `import 'react-colors-beauty/dist/index.umd.es5.development.css';`

**Comment by porameht** [comment]
Thank you very much

**Comment by porameht** [comment]
sorry and thank you i found this error after fix problem follow solution of you suggest. 
![Uploading Screenshot 2567-05-09 at 17.10.02.png…]()
