### ISSUE TITLE
export 'ValueType' was not found in 'rc-input-number'

### ISSUE THREAD

**Issue by porameht** [sleepy-zone/fabritor-web#43]
Good Day,

sorry and thank you i found this error after fix problem follow solution of you suggest. 

<img width="541" alt="Screenshot 2567-05-09 at 17 10 02" src="https://github.com/sleepy-zone/fabritor-web/assets/89307294/e82bfad8-ae1a-4ba2-8911-a556a8c32744">

this repo => [https://github.com/porameht/nextjs-image-editor](https://github.com/porameht/nextjs-image-editor)

**Comment by sleepy-zone** [comment]
you can remove this warning by `npm install  --save react-colors-beauty@2.0.0-beta.2`

**Comment by sleepy-zone** [comment]
I'm planning to implement i18n for fabritor, and I was wondering if I could use your project's English translation directly? Would that be okay?

**Comment by porameht** [comment]
thank you very much, yes that it okay. you have suggest ion in this case to me or not?

**Comment by sleepy-zone** [comment]
thank you!  I'm very happy that you can apply _fabritor_ to your project.☺️
