### ISSUE TITLE
期待图片能支持遮着

### ISSUE THREAD

**Issue by w5w6** [sleepy-zone/fabritor-web#5]
我自己尝试写, 可是技术不好, 没整出来

就是图片可以支持: 心形, 圆形, 不规则图形, 等形状的遮着

用svg, 或者纯色图片进行操作

**Comment by sleepy-zone** [comment]
这个暂时没有时间，但其实使用 fabricjs 比较容易做到的。

**Comment by w5w6** [comment]
> 这个暂时没有时间，但其实使用 fabricjs 比较容易做到的。
> 
> 使用 fabricjs 内置的 Image 对象 和 ClipPath 属性。ClipPath 可以设置为你绘制的 心形、圆形等，心形圆形可以使用内置的对象，也可以使用复杂的 Path 来绘制。

好的, 感谢您的指导, 我去尝试下 😄
