### ISSUE TITLE
导出jpeg有灰色的边框

### ISSUE THREAD

**Issue by bestphp2019** [sleepy-zone/fabritor-web#51]
我将下面方法改为jpeg, 导出后左上和左边有灰色的边框， 源码里面我看作者format是用jpg, 其实fabricjs 不支持jpg 参数， 只支持jpeg。

 https://github.com/sleepy-zone/fabritor-web/blob/3a99d181688ce203d14800b831f867f4d218cb74/src/fabritor/UI/header/Export/index.tsx#L68

我看了这个issue 也有该问题。https://github.com/sleepy-zone/fabritor-web/issues/40

所以现在导出jpg其实还是导出的png只不过把后缀名改成了jpg， 因为png灰色的边不明显。

![image](https://github.com/user-attachments/assets/3dfac5e1-baa9-430d-927d-b51a2ccfe69e)

**Comment by sleepy-zone** [comment]
目前发现可能设置 this.canvas.clipPath 属性导致的，
fabric.js 相关issue: https://github.com/fabricjs/fabric.js/issues/4937
但我按照issue 中的方式操作，并没有奏效。。
