### ISSUE TITLE
请教：如何修改配置，npm run build打包后，可以放置在网站根目录里的二级目录(如：fabritor)里

### ISSUE THREAD

**Issue by WaterCountry** [sleepy-zone/fabritor-web#8]
`framework.js:1 
e {status: 404, statusText: 'Not Found', internal: true, data: 'Error: No route matches URL "/fabritor/index.html"', error: Error: No route matches URL "/fabritor/index.html"
    at ey (http://192.168.1.3/fabritor/js/framew…}
data
: 
"Error: No route matches URL \"/fabritor/index.html\""
error
: 
Error: No route matches URL "/fabritor/index.html" at ey (http://192.168.1.3/fabritor/js/framework.js:1:47360) at http://192.168.1.3/fabritor/js/framework.js:1:23067 at http://192.168.1.3/fabritor/js/87.js:1:34657 at Object.next (http://192.168.1.3/fabritor/js/87.js:1:34762) at r (http://192.168.1.3/fabritor/js/87.js:1:27396) at a (http://192.168.1.3/fabritor/js/87.js:1:27593) at http://192.168.1.3/fabritor/js/87.js:1:27652 at new Promise (<anonymous>) at http://192.168.1.3/fabritor/js/87.js:1:27534 at eJ (http://192.168.1.3/fabritor/js/framework.js:1:24195)
`
网上搜索了一下，在package.json里添加homepage: './fabritor' 无效

**Comment by WaterCountry** [comment]
`import { defineConfig } from '@ice/app';

// The project config, see https://v3.ice.work/docs/guide/basic/config
const minify = process.env.NODE_ENV === 'production' ? 'swc' : false;
export default defineConfig(() => ({
  // Set your configs here.
  outputDir:'poster',
  //hash: true,
  publicPath: '/poster/',
  minify,
  ssr: false,
  ssg: false,
  dataLoader: false,
  server: {
    onDemand: true,
    format: 'esm',
  },

}));`
配置资源路径后，还有一样问题，framework.js有route路由问题

**Comment by WaterCountry** [comment]
vue cli3-cli4 打包后项目在二级路径的方法如下，但是飞冰不知道如何设置？
假设我们的二级目录是：/web
`const router = new VueRouter({
  mode: 'history',
  base: process.env.NODE_ENV === "production" ? "/web" : process.env.BASE_URL,
  routes
})
`

**Comment by WaterCountry** [comment]
vue cli3-cli4 打包后项目在二级路径的方法如下，但是飞冰不知道如何设置？
假设我们的二级目录是：/web
`const router = new VueRouter({
  mode: 'history',
  base: process.env.NODE_ENV === "production" ? "/web" : process.env.BASE_URL,
  routes
})`

**Comment by sleepy-zone** [comment]
publicPath 配合 router baseName 试一下？ https://v3.ice.work/docs/guide/basic/app#router
